version: 2

models:
  - name: fct_payment_reconciliation
    columns:
      - name: order_id
        data_tests:
          - not_null
          - unique

      - name: reconciliation_status
        data_tests:
          - not_null
          - accepted_values:
              arguments:
                values:
                  - MATCHED
                  - ERROR

      - name: is_payment_missing
        data_tests:
          - not_null

      - name: is_merchant_missing
        data_tests:
          - not_null

      - name: is_fee_rate_missing
        data_tests:
          - not_null

      - name: is_order_payment_amount_mismatch
        data_tests:
          - not_null

      - name: is_settlement_missing
        data_tests:
          - not_null

      - name: is_settlement_not_completed
        data_tests:
          - not_null

      - name: is_merchant_mismatch
        data_tests:
          - not_null

      - name: is_gross_amount_mismatch
        data_tests:
          - not_null

      - name: is_fee_amount_mismatch
        data_tests:
          - not_null

      - name: is_net_amount_mismatch
        data_tests:
          - not_null

      - name: is_payment_datetime_invalid
        data_tests:
          - not_null

      - name: is_settlement_datetime_invalid
        data_tests:
          - not_null

      - name: error_count
        data_tests:
          - not_null
